v2-2/config/routes.rb
Rails.application.routes.draw do
  resources :line_items
  resources :books
  resources :users
  resources :zhanr
#  get 'home#index'
  get "books/index"
root :to => 'index#index'
  get 'index', to: 'index#index'
  get 'edit', to: 'books#edit'
  get'books', to: 'books#index'
  get 'new', to:'books#new'
  get 'show', to: 'books#show'

  get 'auth', to: 'auth#index'
  get 'auth_edit', to: 'auth#edit'
  get'auth_books', to: 'auth#index'
  get 'auth_new', to:'auth#new'
  get 'auth_show', to: 'auth#show'

  get 'zhanr', to: 'zhanr#index'
  get 'zhanr_new', to:'zhanr#new'

devise_scope :user do
  get 'sign_up', to: 'devise/registrations#new'
  get 'sign_in', to: 'devise/sessions#new'
  get 'sign_out', to: 'devise/sessions#destroy'
end
get 'show', to: 'home#show'



  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

v2-2/app/models/auth.rb
class Auth < ApplicationRecord
	validates :auth, :book, :presence => true
end

v2-2/app/controllers/auth_controller.rb
class AuthController < ApplicationController
before_action :set_auth, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
    @auths = Auth.all
  end



  # GET /books/1
  # GET /books/1.json
  def show

  end

  # GET /books/new
  def new
    @auth = Auth.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @auth = Auth.new(book_params)

    respond_to do |format|
      if @auth.save
        format.html { redirect_to @auth, notice: 'Автор успішно доданий' }
        format.json { render :show, status: :created, location: @auth }
      else
        format.html { render :new }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @auth, notice: 'Автор успішно змінений' }
        format.json { render :show, status: :ok, location: @auth }
      else
        format.html { render :edit }
        format.json { render json: @auth.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to auths_url, notice: 'Книга успішно видалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Auth.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:auth).permit(:auth, :book)
    end
end

v2-2/app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :set_book, only: [:show, :edit, :update, :destroy]

  # GET /books
  # GET /books.json
  def index
      if params[:search]
        @books = Book.search(params[:search])
      else
        @books = Book.all
      end

  end



  # GET /books/1
  # GET /books/1.json
  def show

  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Книга успішно додана' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Книга успішно змінена' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Книга успішно видалена' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :auth, :zhanr, :pages_qty, :description, :image_url, :mini_description)
    end
end

v2-2/app/controllers/zhanr_controller.rb
class ZhanrController < ApplicationController
end

v2-2/app/helpers/auth_helper.rb
module AuthHelper
end

v2-2/app/helpers/zhanr_helper.rb
module ZhanrHelper
end

v2-2/app/views/books/_form.html.erb
<% if session[:lang] == "ua" 
    text ={
      :label_T => "Назва",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Кількість сторінок",
      :label_D => "Опис",
      :label_MD => "Короткий опис",
      :label_I => "Адреса до картинки",
      :submit => "Підтвердити"
    } 
  elsif session[:lang] == "en" 
    text ={
      :label_T => "Name",
      :label_A => "Author",
      :label_Z => "Genre",
      :label_Q => "Number of pages",
      :label_D => "Description",
      :label_MD => "Mini description",
      :label_I => "Address to the picture",
      :submit => "Submit"
    } 
  elsif session[:lang] == "ru"
    text ={
      :label_T => "Название",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Количество страниц",
      :label_D => "Описание",
      :label_MD => "Краткое описание",
      :label_I => "Адрес к картинке",
      :submit => "Подтвердить"
    } 
  end 
%>
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(book) do |f| %>
      <% if book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_T] %></label>
          <%= f.text_field :title, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_A] %></label>
        <%= f.text_field :auth, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_Z] %></label>
        <%= f.text_field :zhanr, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_Q] %></label>
        <%= f.text_field :pages_qty, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_MD] %></label>
        <%= f.text_area :mini_description, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_D] %></label>
        <%= f.text_area :description, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_I] %></label>
        <%= f.text_field :image_url, :class => "form-control" %>
      </div>

      <div class="actions">
        <input type="submit" name="submit" class="btn" value=<%= text[:submit] %>>
      </div>
    <% end %>
  </div>

v2-2/app/views/books/edit.html.erb
<% if session[:lang] == "ua" 
    text ={
      :h1 => "Редагування книги",
      :show => "Показати",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :h1 => "Editing a book",
      :show => "Show",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :h1 => "Редактирования книги",
      :show => "Показать",
      :back => "Назад"
    } 
  end 
%>
<div class="back">
  <h1 class="col-md-6 col-md-offset-3 text-center back"><%= text[:h1] %></h1>

  <%= render 'form', book: @book %>

  <%= link_to text[:show], @book %> |
  <%= link_to text[:back], books_path %>
</div>

v2-2/app/views/books/index.html.erb
<% if session[:lang] == "ua" 
    text ={
      :label_T => "Назва",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Кількість сторінок",
      :label_D => "Опис",
      :label_I => "Адреса до картинки",
      :h1 => "Книги",
      :show => "Показати",
      :edit => "Редагувати",
      :delete => "Видалити",
      :question => "Ви впевнені?",
      :new => "Додати нову книгу",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :label_T => "Name",
      :label_A => "Author",
      :label_Z => "Genre",
      :label_Q => "Number of pages",
      :label_D => "Description",
      :label_I => "Address to the picture",
      :h1 => "Books",
      :show => "Show",
      :edit => "Edit",
      :delete => "Remove",
      :question => "Are you sure?",
      :new => "Add new book",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :label_T => "Название",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Количество страниц",
      :label_D => "Описание",
      :label_I => "Адрес к картинке",
      :h1 => "Книги",
      :show => "Показать",
      :edit => "Редактировать",
      :delete => "Удалить",
      :question => "Вы уверены?",
      :new => "Добавить новую книгу",
      :back => "Назад"
    } 
  end 
%>

<p id="notice"><%= notice %></p>

<h1 class="col-md-6 col-md-offset-3 text-center back"><%= text[:h1] %></h1>
<div class="container">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-lg-3">
        <div class="box">
          <div class="box-gray aligncenter">
            <h3><%= link_to book.title, book, :class => "product" %></h3>
            <h4><%= book.auth %></h4>
            <div class="icon">
              
              <i class="fa fa-desktop fa-3x"></i>
            </div>
            <p>
              <%= book.mini_description %><br/>
               <%= link_to 'Видалити', book, method: :delete, data: { confirm: 'Ви впевнені?' } %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
 

v2-2/app/views/books/show.html.erb
<% if session[:lang] == "ua" 
    text ={
      :label_T => "Назва",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Кількість сторінок",
      :label_D => "Опис",
      :label_I => "Адреса до картинки",
      :edit => "Редагувати",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :label_T => "Name",
      :label_A => "Author",
      :label_Z => "Genre",
      :label_Q => "Number of pages",
      :label_D => "Description",
      :label_I => "Address to the picture",
      :edit => "Edit",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :label_T => "Название",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Количество страниц",
      :label_D => "Описание",
      :label_I => "Адрес к картинке",
      :edit => "Редактировать",
      :back => "Назад"
    } 
  end 
%>
<div class="col-md-4 col-md-offset-4 back">
  <p id="notice"><%= notice %></p>
  <div class="show_h2 text-center">
    <p>
      <strong><%= @book.title %></strong>
    </p>

    <p>
      <strong><%= @book.auth %></strong>
    </p>
  </div> 
  <div class="show_h2_content">  
    <p>
      <strong><%= text[:label_Z] %></strong>
      <%= @book.zhanr %>
    </p>

    <p>
      <strong><%= text[:label_Q] %></strong>
      <%= @book.pages_qty %>
    </p>

    <p>
      <strong><%= text[:label_D] %></strong>
      <%= @book.description %>
    </p>

    <p>
      <strong><%= text[:label_I] %></strong>
      <%= @book.image_url %>
    </p>
  </div>
  <div class="show_h2_content text-center">
    <%= link_to text[:edit], edit_book_path(@book) %> |
    <%= link_to text[:back], books_path %>
  </div>
</div>

v2-2/app/views/layouts/application.html.erb
<% if session[:lang] == "ua" 
    text ={
      :title => "Бібліотека на RubyOnRails",
      :name => "Бібліотека Ruby On Rails",
      :books => "Книги",
      :registration => "Реєстрація",
      :autorisation => "Авторизація",
      :exit => "Вихід",
      :lang => "Мова",
      :ua => "укр",
      :ru => "рус",
      :en => "анг",
      :submit => "Пошук"
    } 
  elsif session[:lang] == "en" 
    text ={
      :title => "Library on RubyOnRails",
      :name => "Library Ruby On Rails",
      :books => "Books",
      :registration => "Registration",
      :autorisation => "Autorisation",
      :exit => "Exit",
      :lang => "Language",
      :ua => "ua",
      :ru => "ru",
      :en => "en",
      :submit => "Search"
    } 
  elsif session[:lang] == "ru"
    text ={
      :title => "Библиотека на RubyOnRails",
      :name => "Библиотека Ruby On Rails",
      :books => "Книги",
      :registration => "Реєстрация",
      :autorisation => "Авторизация",
      :exit => "Виход",
      :lang => "Язык",
      :ua => "укр",
      :ru => "рус",
      :en => "анг",
      :submit => "Поиск"
    } 
  end 
%>

<!DOCTYPE html>
<html>
  <head>
    <title><%= text[:title] %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div id="wrapper">
    <header>
      <div class="navbar navbar-default navbar-static-top">
        <div class="container">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <h1><a class="navbar-brand" href=""><%= text[:name]%></a></h1>
          </div>
          <div class="navbar-collapse collapse ">
            <ul class="nav navbar-nav">
              <li><%= link_to text[:books], books_path %></li>
              <li class="active"><%= link_to text[:registration], sign_up_path %></li>
              <li><%= link_to text[:autorisation], sign_in_path %></li>
              <li><%= link_to text[:exit], sign_out_path  %></li>

              <li class="dropdown">
                <a href="#" class="dropdown-toggle " data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false"><%= text[:lang] %><b class=" icon-angle-down"></b></a>
                <ul class="dropdown-menu">
                  <li>
                    <a href="index?lang=ua"><%= text[:ua] %></a>
                  </li>
                  <li>
                    <a href="index?lang=ru"><%= text[:ru] %></a>
                  </li>
                  <li>
                    <a href="index?lang=en"><%= text[:en] %></a>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
          <div class="nav navbar-nav right">
            <%= form_tag(books_path, :method => 'get', :class => "form-search") do %>
              <p>
                <%= text_field_tag :search, params[:search], :class => "input-medium search-query" %>
                <%= submit_tag text[:submit], :class => "btn" %>
              </p>
            <% end %>
          </div>
        </div>
      </div>
    </header>
  </div>	
    <%= yield %>
  </body>
</html>

v2-2/app/views/zhanr/_form.html.erb
<% if session[:lang] == "ua" 
    text ={
      :label_T => "Назва",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Кількість сторінок",
      :label_D => "Опис",
      :label_MD => "Короткий опис",
      :label_I => "Адреса до картинки",
      :submit => "Підтвердити"
    } 
  elsif session[:lang] == "en" 
    text ={
      :label_T => "Name",
      :label_A => "Author",
      :label_Z => "Genre",
      :label_Q => "Number of pages",
      :label_D => "Description",
      :label_MD => "Mini description",
      :label_I => "Address to the picture",
      :submit => "Submit"
    } 
  elsif session[:lang] == "ru"
    text ={
      :label_T => "Название",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Количество страниц",
      :label_D => "Описание",
      :label_MD => "Краткое описание",
      :label_I => "Адрес к картинке",
      :submit => "Подтвердить"
    } 
  end 
%>
  <div class="col-md-4 col-md-offset-4">
    <%= form_for(book) do |f| %>
      <% if book.errors.any? %>
        <div id="error_explanation">
          <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

          <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
          </ul>
        </div>
      <% end %>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_T] %></label>
          <%= f.text_field :title, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_A] %></label>
        <%= f.text_field :auth, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_Z] %></label>
        <%= f.text_field :zhanr, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_Q] %></label>
        <%= f.text_field :pages_qty, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_MD] %></label>
        <%= f.text_area :mini_description, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_D] %></label>
        <%= f.text_area :description, :class => "form-control" %>
      </div>

      <div class="form-group">
        <label class="col-xs-2 control-label"><%= text[:label_I] %></label>
        <%= f.text_field :image_url, :class => "form-control" %>
      </div>

      <div class="actions">
        <input type="submit" name="submit" class="btn" value=<%= text[:submit] %>>
      </div>
    <% end %>
  </div>

v2-2/app/views/zhanr/index.html.erb
<% if session[:lang] == "ua" 
    text ={
      :label_T => "Назва",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Кількість сторінок",
      :label_D => "Опис",
      :label_I => "Адреса до картинки",
      :h1 => "Книги",
      :show => "Показати",
      :edit => "Редагувати",
      :delete => "Видалити",
      :question => "Ви впевнені?",
      :new => "Додати нову книгу",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :label_T => "Name",
      :label_A => "Author",
      :label_Z => "Genre",
      :label_Q => "Number of pages",
      :label_D => "Description",
      :label_I => "Address to the picture",
      :h1 => "Books",
      :show => "Show",
      :edit => "Edit",
      :delete => "Remove",
      :question => "Are you sure?",
      :new => "Add new book",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :label_T => "Название",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Количество страниц",
      :label_D => "Описание",
      :label_I => "Адрес к картинке",
      :h1 => "Книги",
      :show => "Показать",
      :edit => "Редактировать",
      :delete => "Удалить",
      :question => "Вы уверены?",
      :new => "Добавить новую книгу",
      :back => "Назад"
    } 
  end 
%>

<p id="notice"><%= notice %></p>

<h1 class="col-md-6 col-md-offset-3 text-center back"><%= text[:h1] %></h1>
<div class="container">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-lg-3">
        <div class="box">
          <div class="box-gray aligncenter">
            <h3><%= link_to book.title, book, :class => "product" %></h3>
            <h4><%= book.auth %></h4>
            <div class="icon">
              
              <i class="fa fa-desktop fa-3x"></i>
            </div>
            <p>
              <%= book.mini_description %><br/>
               <%= link_to 'Видалити', book, method: :delete, data: { confirm: 'Ви впевнені?' } %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
 