v5-2/config/routes.rb
Rails.application.routes.draw do
  resources :vidguks
  get 'abouts/about_us'

  get 'abouts/about_program'

  get 'userparams/new'

  get 'userparams/edit'

  get 'userparams/profile'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :kritics
  resources :zhanrs
  resources :auths
  resources :line_items
  resources :books
  resources :userparams
  resources :vidhucks
  resources :abouts
#  get 'home#index'
  get "books/index"
root :to => 'index#index'
  get 'index', to: 'index#index'

  get 'edit', to: 'books#edit'
  get'books', to: 'books#index'
  get 'new', to:'books#new'
  get 'show', to: 'books#show'

  get 'edit', to: 'zhanr#edit'
  get'zhanr', to: 'zhanr#index'
  get 'new', to:'zhanr#new'
  get 'show', to: 'zhanr#show'

  get 'edit', to: 'auth#edit'
  get'auth', to: 'auth#index'
  get 'new', to:'auth#new'
  get 'show', to: 'auth#show'

  get 'edit', to: 'kritics#edit'
  get'kritics', to: 'kritics#index'
  get 'new', to:'kritics#new'
  get 'show', to: 'kritics#show'

  get 'edit', to: 'vidguks#edit'
  get'vidguks', to: 'vidguks#index'
  get 'new', to:'vidguks#new'
  get 'show', to: 'vidguks#show'


  get 'about_us', to: 'abouts#about_us'
  get 'about_us', to: 'abouts#about_program'

devise_scope :user do
  get 'sign_up', to: 'devise/registrations#new'
  get 'sign_in', to: 'devise/sessions#new'
  get 'sign_out', to: 'devise/sessions#destroy'
end
get 'show', to: 'home#show'
get  'profile', to: 'userparams#profile'
resources :userparams



  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

v5-2/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

v5-2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

v5-2/app/models/auth.rb
class Auth < ApplicationRecord
	def self.search(search)
		where([' auth LIKE ? ', "%#{search}%"])

	end	
end

v5-2/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :vidguks
	has_many :kritics
	belongs_to :zhanr
	validates :title, :auth, :zhanr, :pages_qty, :description, :image_url, :mini_description, :presence => true
	def self.search(search)
		where(['title LIKE ? OR auth LIKE ? OR zhanr LIKE ? OR description LIKE ? ', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])

	end	

end

v5-2/app/models/kritic.rb
class Kritic < ApplicationRecord
	belongs_to :book
	belongs_to :user
	def self.search(search)
		where([' title_book LIKE ? ', "%#{search}%"])

	end	
end

v5-2/app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :book
end

v5-2/app/models/user.rb
class User < ApplicationRecord
  	has_many :books
	has_many :vidguks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :userparam
end

v5-2/app/models/userparam.rb
class Userparam < ApplicationRecord
	belongs_to :user
end

v5-2/app/models/vidguk.rb
class Vidguk < ApplicationRecord
	belongs_to :book
	belongs_to :user
	def self.search(search)
		where([' title_book LIKE ? ', "%#{search}%"])

	end
end

v5-2/app/models/zhanr.rb
class Zhanr < ApplicationRecord
	has_many :books
end

v5-2/app/controllers/books_controller.rb
class BooksController < ApplicationController
 before_action :set_book, only: [:show, :edit, :update, :destroy]
 helper_method :sort_column, :sort_direction
  # GET /books
  # GET /books.json
  def index
    if params[:direction]
      session[:sort_by] = params[:direction]
    else
      session[:sort_by] = "title"
    end
    if params[:type_sort]
      session[:type_sort] = params[:type_sort]
    else
      session[:type_sort] = "asc"
    end
    if params[:search]
      books = Book.search(params[:search])
      books = books.order(sort_column + " " + sort_direction)
      @books = books.paginate(page: params[:page], per_page: 5)
    else
      books = Book.order(sort_column + " " + sort_direction)
      @books = books.paginate(page: params[:page], per_page: 5)
    end
  end

  # GET /books/1
  # GET /books/1.json
  def show
    @kritics = Kritic.search(@book.title)
    @vidguks = Vidguk.search(@book.title)
    @kritic = Kritic.new
    @vidguk = Vidguk.new
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books
  # POST /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: 'Книга успішно додана' }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1
  # PATCH/PUT /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: 'Книга успішно змінена' }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1
  # DELETE /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: 'Книга успішно видалена' }
      format.json { head :no_content }
    end
  end

  private
    def sort_column
      #params[:sort]|| "title"
      params[:sort]||session[:sort_by]
    end

    def sort_direction
      #params[:direction]||"asc"
      params[:direction]||session[:type_sort]
    end
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def book_params
      params.require(:book).permit(:title, :auth, :zhanr, :pages_qty, :description, :image_url, :mini_description)
    end
end

v5-2/app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_user!, except: [:index]

  def index
  end

  def show
  	
 end

end

v5-2/app/helpers/abouts_helper.rb
module AboutsHelper
end

v5-2/app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, :sort => column, :direction => direction
	end
end

v5-2/app/helpers/auths_helper.rb
module AuthsHelper
end

v5-2/app/helpers/books_helper.rb
module BooksHelper
end

v5-2/app/helpers/home_helper.rb
module HomeHelper
end

v5-2/app/helpers/index_helper.rb
module IndexHelper
end

v5-2/app/helpers/kritics_helper.rb
module KriticsHelper
end

v5-2/app/helpers/line_items_helper.rb
module LineItemsHelper
end

v5-2/app/helpers/userparams_helper.rb
module UserparamsHelper
end

v5-2/app/helpers/vidguks_helper.rb
module VidguksHelper
end

v5-2/app/helpers/zhanrs_helper.rb
module ZhanrsHelper
end

v5-2/app/views/books/_form.html.erb
<% if session[:lang] == "ua" 
    text ={
      :label_T => "Назва",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Кількість сторінок",
      :label_D => "Опис",
      :label_MD => "Короткий опис",
      :label_I => "Адреса до картинки",
      :submit => "Підтвердити"
    } 
  elsif session[:lang] == "en" 
    text ={
      :label_T => "Name",
      :label_A => "Author",
      :label_Z => "Genre",
      :label_Q => "Number of pages",
      :label_D => "Description",
      :label_MD => "Mini description",
      :label_I => "Address to the picture",
      :submit => "Submit"
    } 
  elsif session[:lang] == "ru"
    text ={
      :label_T => "Название",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Количество страниц",
      :label_D => "Описание",
      :label_MD => "Краткое описание",
      :label_I => "Адрес к картинке",
      :submit => "Подтвердить"
    } 
  end   
%>
<div class="col-md-4 col-md-offset-4">
  <%= form_for(book) do |f| %>
    <% if book.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>
        <ul>
          <% book.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:label_T] %></label>
      <%= f.text_field :title, :class => "form-control" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:label_A] %></label>
      <%= f.text_field :auth, :class => "form-control" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:label_Z] %></label>
      <%= f.text_field :zhanr, :class => "form-control" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:label_Q] %></label>
      <%= f.text_field :pages_qty, :class => "form-control" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:label_MD] %></label>
      <%= f.text_area :mini_description, :class => "form-control" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:label_D] %></label>
      <%= f.text_area :description, :class => "form-control" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:label_I] %></label>
      <%= f.text_field :image_url, :class => "form-control" %>
    </div>
    <div class="actions">
      <input type="submit" name="submit" class="btn" value=<%= text[:submit] %>>
    </div>
  <% end %>
</div>

v5-2/app/views/books/_form_kritics.html.erb
 <% if session[:lang] == "ua" 
    text ={
      :name => "Ім'я",
      :title_book => "Назва книги",
      :recensiya => "Рецензія",
      :ocinka => "Оцінка",
      :submit => "Підтвердити"
    } 
  elsif session[:lang] == "en" 
    text ={
      :name => "Author",
      :title_book => "Name of book",
      :recensiya => "Review",
      :ocinka => "Rating",
      :submit => "Submit"
    } 
  elsif session[:lang] == "ru"
    text ={
      :name => "Автор",
      :title_book => "Назвиние Книги",
      :recensiya => "Рецензия",
      :ocinka => "Оценка",
      :submit => "Подтвердить"
    } 
  end 
%>
  <%= form_for(kritic) do |f| %>
    <% if kritic.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(kritic.errors.count, "error") %> prohibited this kritic from being saved:</h2>
        <ul>
          <% kritic.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:name] %></label>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.text_field :title_book, :value => @book.title, :class => "form-control", :type => "hidden" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:recensiya] %></label>
      <%= f.text_field :recensiya, :class => "form-control" %>
    </div>
    <div id="rating-form" class="form-group">
      <label class="col-xs-2 control-label"><%= text[:ocinka] %></label>
    </div>
    <div class="actions">
      <input type="submit" name="submit" class="btn" value="<%= text[:submit] %>">
    </div>
  <% end %>
  <script type="text/javascript">
    $('#rating-form').raty({
      path: "/assets/",
      scoreName: "kritic[ocinka]"
    });
  </script>

v5-2/app/views/books/_form_vidguk.html.erb
<% if session[:lang] == "ua" 
    text ={
      :name => "Ім'я",
      :title_book => "Назва книги",
      :recensiya => "Відгук",
      :ocinka => "Дата",
      :submit => "Підтвердити"
    } 
  elsif session[:lang] == "en" 
    text ={
      :name => "Author",
      :title_book => "Name of book",
      :recensiya => "Review",
      :ocinka => "Date",
      :submit => "Submit"
    } 
  elsif session[:lang] == "ru"
    text ={
      :name => "Автор",
      :title_book => "Назвиние Книги",
      :recensiya => "Отзив",
      :ocinka => "Дата",
      :submit => "Подтвердить"
    } 
  end 
%>
  <%= form_for(vidguk) do |f| %>
    <% if vidguk.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(vidguk.errors.count, "error") %> prohibited this vidguk from being saved:</h2>
        <ul>
          <% vidguk.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:name] %></label>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="form-group">
      <%= f.text_field :title_book, :value => @book.title, :class => "form-control", :type => "hidden" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:recensiya] %></label>
      <%= f.text_field :vidguk, :class => "form-control" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:ocinka] %></label>
      <%= f.text_field :date, :class => "form-control" %>
    </div>
    <div class="actions">
      <input type="submit" name="submit" class="btn" value="<%= text[:submit] %>">
    </div>
  <% end %>

v5-2/app/views/books/edit.html.erb
 <% if session[:lang] == "ua" 
    text ={
      :h1 => "Редагування книги",
      :show => "Показати",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :h1 => "Editing a book",
      :show => "Show",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :h1 => "Редактирования книги",
      :show => "Показать",
      :back => "Назад"
    } 
  end 
%>
<div class="back">
  <h1 class="col-md-6 col-md-offset-3 text-center back"><%= text[:h1] %></h1>

  <%= render 'form', book: @book %>

  <%= link_to text[:show], @book %> |
  <%= link_to text[:back], books_path %>
</div>

v5-2/app/views/books/index.html.erb
<% if session[:lang] == "ua" 
    text ={
      :label_T => "Назва",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Кількість сторінок",
      :label_D => "Опис",
      :label_I => "Адреса до картинки",
      :h1 => "Книги",
      :show => "Показати",
      :edit => "Редагувати",
      :delete => "Видалити",
      :question => "Ви впевнені?",
      :new => "Додати нову книгу",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :label_T => "Name",
      :label_A => "Author",
      :label_Z => "Genre",
      :label_Q => "Number of pages",
      :label_D => "Description",
      :label_I => "Address to the picture",
      :h1 => "Books",
      :show => "Show",
      :edit => "Edit",
      :delete => "Remove",
      :question => "Are you sure?",
      :new => "Add new book",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :label_T => "Название",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Количество страниц",
      :label_D => "Описание",
      :label_I => "Адрес к картинке",
      :h1 => "Книги",
      :show => "Показать",
      :edit => "Редактировать",
      :delete => "Удалить",
      :question => "Вы уверены?",
      :new => "Добавить новую книгу",
      :back => "Назад"
    } 
  end 
%>
<p id="notice"><%= notice %></p>
<div class="back">
  <div class="text-center">
    <h1 class="col-md-6 col-md-offset-3"><%= text[:h1] %></h1></br>
    <%= link_to text[:new], new_book_path %>
  </div>
  <br>
</div>
<div class="back">
  <div class="text-left">
    <ul class="list-inline">
      <li>Сортувати за:</li>
      <li>
        <select id="sort" name="sort">
          <option selected value="title">Назвою</option>
          <option value="auth">Автором</option>
          <option value="likes_qty">Лайками</option>
          <option value="dislikes_qty">Дизлайками</option>
        </select>
      </li>
      <li>Тип сортування:</li>
      <li>
        <select id="type_sort" name="type_sort">
          <option selected value="asc">За спаданням</option>
          <option value="desc">За зростанням</option>
        </select>
      </li>
      <li><a id="sorting" class="btn btn-default" href="#">Сортувати</a></li>
    </ul>
  </div>
</div>
<div class="container">
  <div class="row">
    <% @books.each do |book| %>
      <div class="col-lg-3">
        <div class="box">
          <div class="box-gray aligncenter">
            <h3><%= link_to book.title, book, :class => "product" %></h3>
            <h4><a href="/auths?utf8=✓&search=<%= book.auth %>&commit=Пошук" class="product"><%= book.auth %></a></h4>
            <div class="icon">
              
              <i class="fa fa-desktop fa-3x"></i>
            </div>
            <p>
              <%= book.mini_description %><br/>
               <%= link_to text[:delete], book, method: :delete, data: { confirm: text[:question] } %> 
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>
<% if @books.count > 5 %>
  <div class="col-md-6 col-md-offset-3 text-center back">
    <%= will_paginate @books %>
  </div>
<% end %>
<script type="text/javascript">
  $("#sorting").click(function(){
            select = document.getElementById('sort');
            value_sort=select.options[select.selectedIndex].value;
            select=document.getElementById('type_sort');
            type_sort=select.options[select.selectedIndex].value;
            location = "?direction="+type_sort+"&page=1&sort="+value_sort;
        });
</script>

v5-2/app/views/books/new.html.erb
<% if session[:lang] == "ua" 
    text ={
      :h1 => "Додати нову книгу",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :h1 => "Add new book",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :h1 => "Добавить новую книгу",
      :back => "Назад"
    } 
  end 
%>
<div class="back">
  <h1 class="col-md-6 col-md-offset-3 text-center back"><%= text[:h1] %></h1>

  <%= render 'form', book: @book %>

  <%= link_to text[:back], books_path %>
</div>

v5-2/app/views/books/show.html.erb
<% suma_ocinok = 0 %>
<% count = @kritics.count %>
<% @kritics.each do |kritic| %>
  <% suma_ocinok += kritic.ocinka.to_i %>
<% end %>
<% ocinka_kritikiv = suma_ocinok/count %> 
<% if session[:lang] == "ua" 
    text ={
      :label_T => "Назва",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Кількість сторінок",
      :label_D => "Опис",
      :label_I => "Адреса до картинки",
      :edit => "Редагувати",
      :kritic => "Критика",
      :write_kritic => "Написати критику",
      :review => "Відгуки",
      :write_review => "Написати відгук",

      :kritics => "Критика",
      :vidguks => "Відгуки",
      :label_O => "Оцінка",
      :edit => "Редагувати",
      :delete => "Видалити",
      :question => "Ви впевнені?",
      :kritic => "Нова критика",
      :vidguk=> "Новий відгук",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :label_T => "Name",
      :label_A => "Author",
      :label_Z => "Genre",
      :label_Q => "Number of pages",
      :label_D => "Description",
      :label_I => "Address to the picture",
      :edit => "Edit",
      :kritic => "Critics",
      :write_kritic => "Write critics",
      :review => "Reviews",
      :write_review => "Write a review",


      :kritics => "Kritics",
      :vidguks => "Reviews",
      :show => "Show",
      :edit => "Edit",
      :delete => "Remove",
      :question => "Are you sure?",
      :kritic => "New critics",
      :vidguk=> "New review",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :label_T => "Название",
      :label_A => "Автор",
      :label_Z => "Жанр",
      :label_Q => "Количество страниц",
      :label_D => "Описание",
      :label_I => "Адрес к картинке",
      :edit => "Редактировать",
      :kritic => "Критика",
      :write_kritic => "Написать критику",
      :review => "Отзывы",
      :write_review => "Написать отзыв",


      :kritics => "Критика",
      :vidguks => "Отзывы",
      :show => "Показать",
      :edit => "Редактировать",
      :delete => "Удалить",
      :question => "Вы уверены?",
      :new => "Добавить новий отзив",
      :kritic => "Новая критика",
      :vidguk=> "Новий отзыв",
      :back => "Назад"
    } 
  end 
%>
<div class="col-md-4 col-md-offset-4 back">
  <p id="notice"><%= notice %></p>
  <div class="show_h2 text-center">
    <p>
      <strong><%= @book.title %></strong>
    </p>

    <p>
      <strong><%= @book.auth %></strong>
    </p>
  </div> 
  <div class="show_h2_content">  
    <p>
      <strong><%= text[:label_Z] %></strong>
      <%= @book.zhanr %>
    </p>
    <p>
      <ul class="list-inline">
      <li><strong>Оцінка критиків:</strong></li>
      <li><div class="review-rating" data-score="<%= ocinka_kritikiv %>"></div></li>
    </p>
    <p>
      <strong><%= text[:label_Q] %></strong>
      <%= @book.pages_qty %>
    </p>

    <p>
      <strong><%= text[:label_D] %></strong>
      <%= @book.description %>
    </p>

    <p>
      <strong><%= text[:label_I] %></strong>
      <%= @book.image_url %>
    </p>
  </div>
  <div class="show_h2_content text-center">
    <%= link_to text[:edit], edit_book_path(@book) %> |
    <%= link_to text[:back], books_path %>
  </div>
  <br><br>
  <div class="show_h2_content text-right">
    <a href="../kritics?utf8=✓&search=<%= @book.title %>"><%= text[:kritic] %> | <a href="../kritics/new?utf8=✓&search=<%= @book.title %>"><%= text[:write_kritic] %><br>
    <a href="../vidguks?utf8=✓&search=<%= @book.title %>"><%= text[:review] %> | <a href="../vidguks/new?utf8=✓&search=<%= @book.title %>"><%= text[:write_review] %>
  </div>
  <br><br><br>
  <div>
      <a href="#" class="show_kritics" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false"><h2 class="text-left"><%= text[:kritics] %></h2><b class=" icon-angle-down"></b></a></br>
    <div class="block_kritics">
      <% @kritics.each do |kritic| %>
        <div class="vidguk show_h2">
          <ul class="list-inline text-left">
            <li><h3><%= link_to kritic.name, kritic_path, :class => "product" %></h3></li>
            <li><div class="review-rating" data-score="<%= kritic.ocinka %>"></div></li>
          </ul>
          <p><%= kritic.recensiya %></p>
          <div class="text-right">
            <%= link_to text[:delete], kritic, method: :delete, data: { confirm: text[:question] } %> | <%= link_to text[:edit], edit_kritic_path(kritic) %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
    <a href="#" class="add_kritics" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false"><h3 class="text-left"><%= text[:kritic] %></h3><b class=" icon-angle-down"></b></a>
    <div class="form_kritics">
      <%= render 'form_kritics', kritic: @kritic %>
    </div>
    <div id="line"></div>
</div>
<div class="col-md-4 col-md-offset-4 back">
  <div>
      <a href="#" class="show_vidgucs" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false"><h2 class="text-left"><%= text[:vidguks] %></h2></b></a></br>
    <div class="block_vidgucs">
      <% @vidguks.each do |vidguk| %>
        <div class="vidguk show_h2">
          <ul class="list-inline text-left">
            <li><h3><%= link_to vidguk.name, vidguk_path, :class => "product" %></h3></li>
            <li><h3><%= vidguk.date %></h3></li>
          </ul>
          <p><%= vidguk.vidguk %></p>
          <div class="text-right">
            <%= link_to text[:delete], vidguk, method: :delete, data: { confirm: text[:question] } %> | <%= link_to text[:edit], edit_vidguk_path(vidguk) %>
          </div>
        </div>
      <% end %>
    </div>
  <a href="#" class="add_vidgucs" data-toggle="dropdown" data-hover="dropdown" data-delay="0" data-close-others="false"><h3 class="text-left"><%= text[:vidguk] %></h3><b class=" icon-angle-down"></b></a>
  <div class="form_vidgucs">
    <%= render 'form_vidguk', vidguk: @vidguk %>
  </div>
</div>
 <script type="text/javascript">
    $('.review-rating').raty({
      readOnly: true,
      score: function(){
         return $(this).attr("data-score");
      },
      path: "/assets/"
    });
  </script>