v5-2/config/routes.rb
Rails.application.routes.draw do
  resources :vidguks
  get 'abouts/about_us'

  get 'abouts/about_program'

  get 'userparams/new'

  get 'userparams/edit'

  get 'userparams/profile'

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :kritics
  resources :zhanrs
  resources :auths
  resources :line_items
  resources :books
  resources :userparams
  resources :vidhucks
  resources :abouts
#  get 'home#index'
  get "books/index"
root :to => 'index#index'
  get 'index', to: 'index#index'

  get 'edit', to: 'books#edit'
  get'books', to: 'books#index'
  get 'new', to:'books#new'
  get 'show', to: 'books#show'

  get 'edit', to: 'zhanr#edit'
  get'zhanr', to: 'zhanr#index'
  get 'new', to:'zhanr#new'
  get 'show', to: 'zhanr#show'

  get 'edit', to: 'auth#edit'
  get'auth', to: 'auth#index'
  get 'new', to:'auth#new'
  get 'show', to: 'auth#show'

  get 'edit', to: 'kritics#edit'
  get'kritics', to: 'kritics#index'
  get 'new', to:'kritics#new'
  get 'show', to: 'kritics#show'

  get 'edit', to: 'vidguks#edit'
  get'vidguks', to: 'vidguks#index'
  get 'new', to:'vidguks#new'
  get 'show', to: 'vidguks#show'


  get 'about_us', to: 'abouts#about_us'
  get 'about_us', to: 'abouts#about_program'

devise_scope :user do
  get 'sign_up', to: 'devise/registrations#new'
  get 'sign_in', to: 'devise/sessions#new'
  get 'sign_out', to: 'devise/sessions#destroy'
end
get 'show', to: 'home#show'
get  'profile', to: 'userparams#profile'
resources :userparams



  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

v5-2/app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

v5-2/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

v5-2/app/models/auth.rb
class Auth < ApplicationRecord
	def self.search(search)
		where([' auth LIKE ? ', "%#{search}%"])

	end	
end

v5-2/app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :vidguks
	has_many :kritics
	belongs_to :zhanr
	validates :title, :auth, :zhanr, :pages_qty, :description, :image_url, :mini_description, :presence => true
	def self.search(search)
		where(['title LIKE ? OR auth LIKE ? OR zhanr LIKE ? OR description LIKE ? ', "%#{search}%", "%#{search}%", "%#{search}%", "%#{search}%"])

	end	

end

v5-2/app/models/kritic.rb
class Kritic < ApplicationRecord
	belongs_to :book
	belongs_to :user
	def self.search(search)
		where([' title_book LIKE ? ', "%#{search}%"])

	end	
end

v5-2/app/models/line_item.rb
class LineItem < ApplicationRecord
	belongs_to :book
end

v5-2/app/models/user.rb
class User < ApplicationRecord
  	has_many :books
	has_many :vidguks
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :userparam
end

v5-2/app/models/userparam.rb
class Userparam < ApplicationRecord
	belongs_to :user
end

v5-2/app/models/vidguk.rb
class Vidguk < ApplicationRecord
	belongs_to :book
	belongs_to :user
	def self.search(search)
		where([' title_book LIKE ? ', "%#{search}%"])

	end
end

v5-2/app/models/zhanr.rb
class Zhanr < ApplicationRecord
	has_many :books
end

v5-2/app/controllers/home_controller.rb
class HomeController < ApplicationController
before_action :authenticate_user!, except: [:index]

  def index
  end

  def show
  	
 end

end

v5-2/app/controllers/vidguks_controller.rb
class VidguksController < InheritedResources::Base
before_action :set_vidguk, only: [:show, :edit, :update, :destroy]
before_action :authenticate_user!, only: [:new, :edit]
  # GET /vidguks
  # GET /vidguks.json
  def index
    if params[:search]
      @vidguks = Vidguk.search(params[:search])
      @title = params[:search]
    else
      redirect_to(books_path)
    end
  end

  # GET /vidguks/1
  # GET /vidguks/1.json
  def show
  end

  # GET /vidguks/new
  def new
    if params[:search]
      @kritics = params[:search]
    else
      redirect_to(books_path)
    end
    @vidguk = Vidguk.new
  end

  # GET /vidguks/1/edit
  def edit
  end

  # POST /vidguks
  # POST /vidguks.json
  def create
    @vidguk = Vidguk.new(vidguk_params)

    respond_to do |format|
      if @vidguk.save
        format.html { redirect_to @vidguk, notice: 'Vidguk was successfully created.' }
        format.json { render :show, status: :created, location: @vidguk }
      else
        format.html { render :new }
        format.json { render json: @vidguk.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vidguks/1
  # PATCH/PUT /vidguks/1.json
  def update
    respond_to do |format|
      if @vidguk.update(vidguk_params)
        format.html { redirect_to @vidguk, notice: 'Vidguk was successfully updated.' }
        format.json { render :show, status: :ok, location: @vidguk }
      else
        format.html { render :edit }
        format.json { render json: @vidguk.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vidguks/1
  # DELETE /vidguks/1.json
  def destroy
    @vidguk.destroy
    respond_to do |format|
      format.html { redirect_to vidguks_url, notice: 'Line item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_vidguk
      @vidguk = Vidguk.find(params[:id])
    end

    def vidguk_params
      params.require(:vidguk).permit(:name, :title_book, :vidguk, :date)
    end
end

v5-2/app/helpers/abouts_helper.rb
module AboutsHelper
end

v5-2/app/helpers/application_helper.rb
module ApplicationHelper
	def sortable(column, title = nil)
		title ||= column.titleize
		direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
		link_to title, :sort => column, :direction => direction
	end
end

v5-2/app/helpers/auths_helper.rb
module AuthsHelper
end

v5-2/app/helpers/books_helper.rb
module BooksHelper
end

v5-2/app/helpers/home_helper.rb
module HomeHelper
end

v5-2/app/helpers/index_helper.rb
module IndexHelper
end

v5-2/app/helpers/kritics_helper.rb
module KriticsHelper
end

v5-2/app/helpers/line_items_helper.rb
module LineItemsHelper
end

v5-2/app/helpers/userparams_helper.rb
module UserparamsHelper
end

v5-2/app/helpers/vidguks_helper.rb
module VidguksHelper
end

v5-2/app/helpers/zhanrs_helper.rb
module ZhanrsHelper
end

v5-2/app/views/vidguks/_form.html.erb
<% if session[:lang] == "ua" 
    text ={
      :name => "Ім'я",
      :title_book => "Назва книги",
      :recensiya => "Відгук",
      :ocinka => "Дата",
      :submit => "Підтвердити"
    } 
  elsif session[:lang] == "en" 
    text ={
      :name => "Author",
      :title_book => "Name of book",
      :recensiya => "Review",
      :ocinka => "Date",
      :submit => "Submit"
    } 
  elsif session[:lang] == "ru"
    text ={
      :name => "Автор",
      :title_book => "Назвиние Книги",
      :recensiya => "Отзив",
      :ocinka => "Дата",
      :submit => "Подтвердить"
    } 
  end 
%>
  <%= form_for(vidguk) do |f| %>
    <% if vidguk.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(vidguk.errors.count, "error") %> prohibited this vidguk from being saved:</h2>
        <ul>
          <% vidguk.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:name] %></label>
      <%= f.text_field :name, :class => "form-control" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:title_book] %></label>
      <% if @kritics %>
        <%= f.text_field :title_book, :value => @kritics, :class => "form-control" %>
      <% else %>
        <%= f.text_field :title_book, :class => "form-control" %>
      <% end %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:recensiya] %></label>
      <%= f.text_field :vidguk, :class => "form-control" %>
    </div>
    <div class="form-group">
      <label class="col-xs-2 control-label"><%= text[:ocinka] %></label>
      <%= f.text_field :date, :class => "form-control" %>
    </div>
    <div class="actions">
      <input type="submit" name="submit" class="btn" value="<%= text[:submit] %>">
    </div>
  <% end %>

v5-2/app/views/vidguks/edit.html.erb
 <% if session[:lang] == "ua" 
    text ={
      :h1 => "Редагування",
      :show => "Показати",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :h1 => "Editing",
      :show => "Show",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :h1 => "Редактирования",
      :show => "Показать",
      :back => "Назад"
    } 
  end 
%>
<div class="back">
  <h1 class="col-md-6 col-md-offset-3 text-center back"><%= text[:h1] %></h1>
  <%= render 'form', vidguk: @vidguk %>
	<%= link_to text[:show], @vidguk %> |
	<%= link_to text[:back], vidguks_path %>
</div>

v5-2/app/views/vidguks/index.html.erb
<% if session[:lang] == "ua" 
    text ={
      :h1 => "Критика",
      :label_A => "Автор",
      :label_B => "Назва книги",
      :label_O => "Оцінка",
      :show => "Показати",
      :edit => "Редагувати",
      :delete => "Видалити",
      :question => "Ви впевнені?",
      :new => "Додати новий відгук",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :h1 => "Kritics",
      :label_A => "Author",
      :show => "Show",
      :edit => "Edit",
      :delete => "Remove",
      :question => "Are you sure?",
      :new => "Add new review",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :h1 => "Критика",
      :label_A => "Автор",
      :show => "Показать",
      :edit => "Редактировать",
      :delete => "Удалить",
      :question => "Вы уверены?",
      :new => "Добавить новий отзив",
      :back => "Назад"
    } 
  end 
%>
<p id="notice"><%= notice %></p>
<div class="text-center back">
  <h1 class="col-md-6 col-md-offset-3"><%= text[:h1] %></h1></br>
  <h2 class="col-md-6 col-md-offset-3 back"><%= @title %></h2></br>
  <%= link_to text[:new], new_kritic_path %>
</div>
<div class="container">
  <div class="row">
    <% @vidguks.each do |vidguk| %>
      <div class="col-lg-3">
        <div class="box">
          <div class="box-gray aligncenter">
            <h3><%= link_to vidguk.name, vidguk, :class => "product" %></h3>
            <h4><a href="/books?utf8=✓&search=<%= vidguk.title_book %>&commit=Пошук" class="product"><%= vidguk.title_book %></a></h4>
            <div class="icon">
              
              <i class="fa fa-desktop fa-3x"></i>
            </div>
            <p>
              <%= vidguk.date %><br>
              <%= link_to text[:delete], vidguk, method: :delete, data: { confirm: text[:question] } %> | <%= link_to text[:edit], edit_vidguk_path(vidguk) %>
            </p>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>




<p id="notice"><%= notice %></p>

<h1>Vidguks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Title book</th>
      <th>Vidguk</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @vidguks.each do |vidguk| %>
      <tr>
        <td><%= vidguk.name %></td>
        <td><%= vidguk.title_book %></td>
        <td><%= vidguk.vidguk %></td>
        <td><%= vidguk.date %></td>
        <td><%= link_to 'Show', vidguk %></td>
        <td><%= link_to 'Edit', edit_vidguk_path(vidguk) %></td>
        <td><%= link_to 'Destroy', vidguk, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Vidguk', new_vidguk_path %>

v5-2/app/views/vidguks/new.html.erb
<% if session[:lang] == "ua" 
    text ={
      :h1 => "Додати новий відгук",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :h1 => "Add new review",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :h1 => "Добавить новой отзив",
      :back => "Назад"
    } 
  end 
%>
<div class="back">
  <h1 class="col-md-6 col-md-offset-3 text-center back"><%= text[:h1] %></h1>

  <%= render 'form', vidguk: @vidguk %>
  <%= link_to text[:back], vidguks_path %>
</div>

v5-2/app/views/vidguks/show.html.erb
<% if session[:lang] == "ua" 
    text ={
      :name => "Ім'я",
      :title_book => "Назва книги",
      :recensiya => "Відгук",
      :ocinka => "Дата",
      :submit => "Підтвердити",
      :edit => "Редагувати",
      :back => "Назад"
    } 
  elsif session[:lang] == "en" 
    text ={
      :name => "Author",
      :title_book => "Name of book",
      :recensiya => "Review",
      :ocinka => "Date",
      :submit => "Submit",
      :edit => "Edit",
      :back => "Back"
    } 
  elsif session[:lang] == "ru"
    text ={
      :name => "Автор",
      :title_book => "Назвиние Книги",
      :recensiya => "Отзив",
      :ocinka => "Дата",
      :submit => "Подтвердить",
      :edit => "Редактировать",
      :back => "Назад"
    } 
  end 
%>
<div class="col-md-4 col-md-offset-4 back">
  <p id="notice"><%= notice %></p>
  <div class="show_h2 text-center">

    <p>
      <strong><%= @vidguk.name %></strong>
    </p>
  </div> 
  <div class="show_h2_content">
    <p>
      <strong><%= text[:title_book] %></strong>
      <%= @vidguk.title_book %>
    </p>
    <p>
      <strong><%= text[:ocinka] %></strong>
      <%= @vidguk.vidguk %>
    </p>
    <p>
      <strong><%= text[:recensiya] %></strong>
      <%= @vidguk.date %>
    </p>
  </div>
  <div class="show_h2_content text-center">
    <%= link_to text[:edit], edit_vidguk_path(@vidguk) %> |
	<%= link_to text[:back], vidguks_path %>
  </div>
</div>